load initial-states

mod RAMP-SNOW-ANALYSIS is
  including INITIAL-STATES .
  including APMAUDE .
  including MODEL-CHECKER .
  including RAMP-F .

  subsort Config < State .

  eq LIMIT = 1.0e+100 .

  op initConfig : -> Config .
  eq initConfig = run(initState,LIMIT) .

  ops x y z : -> Key .
  ops tb r1 r2 r3 t1 t2 t3 t4 d1 d2 d3 m : -> Address .
  ops xl yl zl : -> LocalVar .

  *** non-replicated setting: DCS is fixed as 1
  --- init(RTX,WTX,RWTX,CLS,DCS,REPLS,KEYS,ROPS,WOPS,RWOPS,KAD) 
  eq initState = init(4,4,0,5,1,3,4,2,2,0,zipf) .


  ---(
  eq initState = { 0.0 | nil} < m : Monitor | log: noRecord > 
                 < tb : Table | table: ([replicatingSites(x, 1 ;; 3) ;; replicatingSites(y, 2 ;; 4)]),
                                datacenter: (dc(d1,1 ; 2) ; dc(d2,3 ; 4)) > 
                 [ 1.0, 11 <- start ] [ 2.0, 12 <- start ]
	 < 11 : Client | gotTxns: < 11 . 1 : Txn | operations: ((11 . 1 . 1 xl :=read x) (11 . 1 . 2 yl :=read y)), readSet: empty, 
                                               latest: empty, localVars: (xl |-> [0], yl |-> [0]),
  					                           voteSites: noVS, 1stGetSites: no1st,
  					                           2ndGetSites: no2nd, commitSites: noVS,
											   txnSqn: -1.0 >, 
                        
                     executing: noActor, 
                     committed: emptyTxnList,
					 dc: d1 >
	 < 12 : Client | gotTxns: < 12 . 1 : Txn | operations: (write(12 . 1 . 1,x,1) write(12 . 1 . 2,y,1)), readSet: empty, 
                                               latest: empty, localVars: (xl |-> [0], yl |-> [0]),
					                           voteSites: noVS, 1stGetSites: no1st,
					                           2ndGetSites: no2nd, commitSites: noVS,
											   txnSqn: -1.0 >, 
                     executing: noActor, 
                     committed: emptyTxnList,
					 dc: d2 >
					   
     < 1 : Replica | datastore: version(x,[0],eptTS,empty), latestCommit: empty > 
     < 2 : Replica | datastore: version(y,[0],eptTS,empty), latestCommit: empty >
     < 3 : Replica | datastore: version(x,[0],eptTS,empty), latestCommit: empty >
     < 4 : Replica | datastore: version(y,[0],eptTS,empty), latestCommit: empty > .
  )

  --- Metrics
  vars T T' T1 T2 T1' T2' NUMBER : Float .
  var C : Config .
  vars M TID TID' : Address .
  vars RECORD RECORD' RECORD'' : Record . 
  vars READS READS' WRITES WRITES' VS VS' : Versions .
  var FLAG : Bool .
  vars TS TS' TS1 TS2 TS1' TS2' : Timestamp .
  vars MD MD' MD1 MD2 MD1' MD2' : KeySet .
  vars V V' V1 V2 V1' V2' : Value .
  vars K K1 K2 : Key .
  vars TIDS TIDS' : AddressSet .
  var AS : AttributeSet .

  --- Throughput
  op totalRunTime : Record -> Float .
  op trt : Record Float -> Float .
  eq totalRunTime(RECORD) = trt(RECORD,0.0) .
  eq trt((record(TID,T1,T2,READS,WRITES,FLAG) ; RECORD),T) = 
       if T2 > T
         then trt(RECORD,T2)
         else trt(RECORD,T)
       fi .
  eq trt(noRecord,T) = T .
         
  op throughput : Config -> Float .
  eq throughput(< M : Monitor | log: RECORD, AS > C) = committedNumber(RECORD) / totalRunTime(RECORD) .

  op committedNumber : Record -> Float .
  op $committedNumber : Record Float -> Float .
  eq committedNumber(RECORD) = $committedNumber(RECORD,0.0) .
  eq $committedNumber((record(TID,T1,T2,READS,WRITES,true) ; RECORD),NUMBER) = 
       $committedNumber(RECORD,NUMBER + 1.0) .
  eq $committedNumber((record(TID,T1,T2,READS,WRITES,false) ; RECORD),NUMBER) = 
       $committedNumber(RECORD,NUMBER) .
  eq $committedNumber(noRecord,NUMBER) = NUMBER .

  --- Commit Rate
  op commitRate : Config -> Float .
  eq commitRate(< M : Monitor | log: RECORD, AS > C) = committedNumber(RECORD) / totalNumber(RECORD) .

  op totalNumber : Record -> Float .
  op $totalNumber : Record Float -> Float .
  eq totalNumber(RECORD) = $totalNumber(RECORD,0.0) .
  eq $totalNumber((record(TID,T1,T2,READS,WRITES,FLAG) ; RECORD),NUMBER) = 
       $totalNumber(RECORD,NUMBER + 1.0) .
  eq $totalNumber(noRecord,NUMBER) = NUMBER .  

  --- Avg Latency
  op avgLatency : Config -> Float .
  eq avgLatency(< M : Monitor | log: RECORD, AS > C) = totalLatency(RECORD) / committedNumber(RECORD) .
  
  op totalLatency : Record -> Float .
  op $totalLatency : Record Float -> Float .
  eq totalLatency(RECORD) = $totalLatency(RECORD,0.0) .
  eq $totalLatency((record(TID,T1,T2,READS,WRITES,true) ; RECORD),NUMBER) =
       $totalLatency(RECORD,NUMBER + T2 - T1) .
  eq $totalLatency((record(TID,T1,T2,READS,WRITES,false) ; RECORD),NUMBER) = 
       $totalLatency(RECORD,NUMBER) .
  eq $totalLatency(noRecord,NUMBER) = NUMBER .
  
  *** 
  op pf : Config -> Float .
  
  *** concurrent reads
  *** assume txns are always committed; owise, need to match TID and "true" TID in LOG
  op cr : Config -> Float .
  op isCr : Config -> Float .
    
*** ryw; ryw vs pf vs cr
*** read latency

  *** read atomicity
  op ra : Config -> Float .
  

  --- PVESTA interfaces
  eq val(0,C) = throughput(C) .
  eq val(1,C) = avgLatency(C) .
  eq val(2,C) = commitRate(C) .
  eq val(3,C) = pf(C) .
  eq val(4,C) = cr(C) .
  eq val(5,C) = isCr(C) .
  eq val(6,C) = ra(C) .
        
endm

set clear rules off .
rewrite initConfig .